apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-vc
  labels:
    app: mariadb
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWrite
  resources:
    requests:
      storage: 2Gi

