apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - args:
            - sh
            - -c
            - python manage.py migrate && python manage.py runserver 0.0.0.0:8000
          image: bettermercury/django-app
          name: web-tsic2
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
