apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\ricardolb\repos\proyecto-tsic\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\ricardolb\repos\proyecto-tsic\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            - sh
            - -c
            - python manage.py migrate && python manage.py runserver 0.0.0.0:8000
          image: web
          name: web-tsic2
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
