# Generated by Django 5.0.6 on 2024-05-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="icos",
            field=models.ImageField(null=True, upload_to="icons"),
        ),
    ]
