# Generated by Django 5.0.6 on 2024-05-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_app_icos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="icos",
            new_name="icons",
        ),
    ]
