version: '3.8'
services:
  devcontainer:
    container_name: "web_tsic2"
    image: "mcr.microsoft.com/devcontainers/python:1-3.12-bullseye"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    container_name: "db-tsic2"
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tienda-apps
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb-data: